### ISSUE TITLE
how to Install MMDetection.

### ISSUE THREAD

**Issue by palashmoon** [wenzhengzeng/MPEblink#3]
I am really inspired by your work. can you please help me out on how to Install MMDetection? or do we only need to install mmcv?

**Comment by wenzhengzeng** [comment]
Thanks for your appreciation of our work. You need to install [MMCV](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) first. It is recommended to use version 1.4.8. After that, run the following commands to install MMDetection: 
  ```bash
     cd MPEblink
     pip install -v -e .

**Comment by palashmoon** [comment]
Thank you @wenzhengzeng for the reply. This is the version I have installed for mmcv and mmdet as you mentioned. 
![image](https://github.com/wenzhengzeng/MPEblink/assets/14892577/3c895c40-db46-41d6-9956-1c057bdecc55)
but this is the error I am getting now. 

Traceback (most recent call last):
  File "./scripts/feature_extraction/dvlog/extract_blink_patterns.py", line 14, in <module>
    from mmdet.apis import init_detector
  File "/palashm/multimodal-depression-from-video/scripts/conda_envs/feature_extractors/MPEblink/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/palashm/multimodal-depression-from-video/scripts/conda_envs/feature_extractors/MPEblink/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/opt/conda/envs/instblink/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/conda/envs/instblink/lib/python3.7/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "/opt/conda/envs/instblink/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/envs/instblink/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by wenzhengzeng** [comment]
I guess maybe there is some incompatibility (e.g., CUDA version). So please refer to the [master branch](https://mmcv.readthedocs.io/en/master/get_started/installation.html) of the MMCV installation documentation, then choose the correct command based on your actual environment. 
<img width="817" alt="433c32c54b6bb35c006d6df42630c88" src="https://github.com/wenzhengzeng/MPEblink/assets/49069169/58491678-707b-4132-bf36-e947c741338f">

If this is truly the cause, don't simply replace the old one; uninstall it first.
  ```bash
     pip uninstall mmcv
     pip uninstall mmdet
 ```
Besides, to seek other possible solutions, you can also refer to the [MCGaze](https://github.com/zgchen33/MCGaze/issues?q=is%3Aissue+is%3Aclosed) project, whose environment also inherits from InstBlink.
